#
# Module manifest for module 'cIniFileResources'
#
# Generated by: John Roos
#
# Generated on: 2016-03-28
#

@{

# Version number of this module.
ModuleVersion = '0.1'

# ID used to uniquely identify this module
GUID = 'fa7d1e48-a6bd-47b5-bee4-a0a2f1f7ff02'

# Author of this module
Author = 'John Roos'

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

}