#
# Module manifest for module 'cIniFile2'
#
# Generated by: John Roos
#
# Generated on: 2016-03-28
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'cIniFile2.schema.psm1'

# Version number of this module.
ModuleVersion = '0.1'

# ID used to uniquely identify this module
GUID = 'ea7249e0-9ba9-45c9-a441-675e2c8a683b'

# Author of this module
Author = 'John Roos'

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

}